### ISSUE TITLE
M3: 拡張フック - YAML/JSON設定、テーマ切替

### ISSUE THREAD

**Issue by GohtaOkuno** [GohtaOkuno/Kumihan-Formatter#10]
## 概要
設定ファイルによるカスタマイズ機能を実装する。

## タスク
- [ ] YAML/JSON設定ファイルの読み込み
- [ ] カスタムマーカーの定義機能
- [ ] CSSテーマの切り替え機能
- [ ] フォント設定のカスタマイズ
- [ ] 設定ファイルのバリデーション

## 設定ファイル例
```yaml
markers:
  custom1:
    tag: div
    class: custom-style
    
theme: dark
font-family: "Noto Sans JP"
```

## 受け入れ条件
- --config フラグで設定ファイルを指定できる
- 不正な設定ファイルでもデフォルトで動作する
